[tool.poetry]
name = "latex-tutorial"
version = "1.0"
description = "Get up and running with Latex!"
authors = ["Dustin Enyeart"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sphinx = "^8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
